### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by hgjanu** [delebota/java-generator#14]
[Enter steps to reproduce:]

1. Create an empty java source file
2. Call 'Packages' -> 'Java Generator' -> 'Builder'

**Atom**: 1.14.1 x64
**Electron**: 1.3.13
**OS**: linux 4.9.8-pclos1
**Thrown From**: [java-generator](https://github.com/delebota/java-generator) package 2.2.0

### Stack Trace

Uncaught TypeError: Cannot read property '1' of null

```
At /home/janu/.atom/packages/java-generator/lib/parser.coffee:65

TypeError: Cannot read property '1' of null
    at Parser.module.exports.Parser.getClassName (/packages/java-generator/lib/parser.coffee:65:22)
    at Object.createBuilder (/packages/java-generator/lib/java-generator.coffee:155:28)
    at Object.generateBuilder (/packages/java-generator/lib/java-generator.coffee:305:17)
    at /packages/java-generator/lib/java-generator.coffee:10:84)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1158:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -0:49.5.0 autocomplete-java:refresh-project (input.hidden-input)
     -0:33.3.0 java-generator:generate-builder (input.hidden-input)
```

### Non-Core Packages

```
autocomplete-java 1.2.5 
java-generator 2.2.0 
java-importer 1.4.1 
linter 1.11.18 
linter-javac 1.9.4 
```

**Comment by delebota** [comment]
Pushed 2.2.3 to fix this and a few other minor issues.
